# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
            ],
            managers=[
                ('logMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
